export { articleDetaliReducer } from './model/slice'
export { ArticleCommentBlockReducer } from './model/slice/ArticleCommentSlice'
export { ArticleCommentSchema } from './model/types/ArticleCommentSchema'
export { ArticleDetaliPageAsync as ArticleDetaliPage } from './ui/ArticleDetaliPage/ArticleDetaliPageAsync'
export { ArticleRecommendatiosSchema } from './model/types/ArticleRecommendatiosSchema'
export { ArticleDetaliPageSchema } from './model/types/index'
