export { articleDetaliReducer } from './model/slice'
export { ArticleCommentBlockReducer } from './model/slice/ArticleCommentSlice'
export type { ArticleCommentSchema } from './model/types/ArticleCommentSchema'
export { ArticleDetaliPageAsync as ArticleDetaliPage } from './ui/ArticleDetaliPage/ArticleDetaliPageAsync'
export type { ArticleRecommendatiosSchema } from './model/types/ArticleRecommendatiosSchema'
export type { ArticleDetaliPageSchema } from './model/types/index'
