name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

    jobs:
  integration:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
        steps:
      name: build production
      - run: npm run build:prod
      name: eslint
      - run: npm run lint:ts
      name: stylelint
      - run: npm run lint:ts
      name: unit test
      - run: npm run unit